### ISSUE TITLE
Undefined property: stdClass::$nullable

### ISSUE THREAD

**Issue by symut** [pandigresik/easyAPI#6]
pak, saya coba pakai ini dengan database SQLServer muncul error => "Undefined property: stdClass::$nullable at VENDORPATH/asligresik/easyapi/src/Commands/API/GeneratorCommand.php:192"

<img width="599" alt="Screen Shot 2022-10-08 at 09 42 06" src="https://user-images.githubusercontent.com/31498966/194684476-60a05eda-9394-4062-b97f-fb479342bb35.png">

gimana solusinya ya? 
sudah coba ganti $nullable => $null => $is_nullable masih error

Q = apakah wajib harus membuat file migration sebelum generate?

terimakasih

**Comment by pandigresik** [comment]
bisa upgrade package asligresik/easyapi ke versi v0.1.0

**Comment by pandigresik** [comment]
bisa upgrade package asligresik/easyapi ke versi v0.1.0

**Comment by symut** [comment]
oke pak, kita coba lagi
